#ifndef LANGMANAGER_GLOBAL_H
#define LANGMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LANGMANAGER_LIBRARY)
#  define LANGMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LANGMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LANGMANAGER_GLOBAL_H
