#ifndef RESOURCEMANAGER_GLOBAL_H
#define RESOURCEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RESOURCEMANAGER_LIBRARY)
#  define RESOURCEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RESOURCEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RESOURCEMANAGER_GLOBAL_H
